# config to use RTMP with http hooks to authorize clients

max_connections     1000;
daemon              off;
srs_log_tank        console;
#srs_log_file ./objs/srs.log;

# RTMP server configuration
rtmp {
	listen              1935;
	chunk_size 60000;
}

vhost __defaultVhost__ {
	tcp_nodelay on;
	min_latency on;

	play {
		gop_cache off;
		queue_length 10;
		mw_latency 100;
	}

	publish {
		mr off;
	}

	http_hooks {
		enabled         on;
		on_publish      http://127.0.0.1:8085/api/v1/streams http://localhost:8085/api/v1/streams;
		on_unpublish    http://127.0.0.1:8085/api/v1/streams http://localhost:8085/api/v1/streams;
		on_play         http://127.0.0.1:8085/api/v1/sessions http://localhost:8085/api/v1/sessions;
		on_stop         http://127.0.0.1:8085/api/v1/sessions http://localhost:8085/api/v1/sessions;
	}
}
